//! Manual, authenticated updates for wizard-installed Linux single nodes.
//!
//! The unprivileged server discovers and stages signed releases. A separately
//! installed systemd oneshot invokes the privileged helper for the final swap.

use std::collections::BTreeMap;
use std::fs;
use std::io::Read;
use std::path::{Component, Path, PathBuf};
use std::process::Command;
use std::sync::Arc;
use std::time::{Duration, Instant};

use base64::Engine;
use ed25519_dalek::pkcs8::DecodePublicKey;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use semver::Version;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::sync::Mutex;
use uuid::Uuid;

use crate::build_info;
use crate::config::{ServerConfig, ServerMode};
use crate::errors::{Result, UdsError};

/// Official release API used for manual UDS updates.
const RELEASES_API: &str = "https://api.github.com/repos/MindWorkAI/UpdateDeliveryServer/releases";

/// Public signing key committed with the release workflow.
const UPDATE_PUBLIC_KEY: &str = include_str!("../release/uds-update-public-key.pem");

/// Releases shown by the explicit regular/prerelease chooser.
#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ReleaseKind {
    /// Published releases intended for normal production selection.
    Regular,

    /// Prereleases shown only after the administrator switches lists.
    Prerelease,
}

/// One verified, newer GitHub release offered to an administrator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AvailableRelease {
    /// Exact semantic version selected by the administrator.
    pub version: String,

    /// Build number signed in to the release manifest.
    pub build: u64,

    /// Release notes displayed before confirmation.
    pub notes: String,

    /// Whether GitHub marks this release as a prerelease.
    pub prerelease: bool,
}

/// Node capability and releases returned by the update discovery endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseResponse {
    /// Stable identity of the local node.
    pub node_id: Uuid,

    /// The currently running UDS version.
    pub version: String,

    /// Currently running UDS build number.
    pub build: u64,

    /// Whether this exact installation supports the manual workflow.
    pub update_supported: bool,

    /// Safe explanation when updates are unavailable.
    pub unavailable_reason: Option<String>,

    /// Verified releases newer than the running version.
    pub releases: Vec<AvailableRelease>,
}

/// Client-generated, idempotent request for one exact version.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct StartUpdateRequest {
    /// Stable operation identifier generated before the first POST.
    pub operation_id: Uuid,

    /// Local target node; fleet targeting is deliberately unavailable.
    pub node_id: Uuid,

    /// Exact semantic version chosen from the discovery response.
    pub version: String,

    /// Explicit opt-in required when the selected release is a prerelease.
    pub allow_prerelease: bool,
}

/// Durable lifecycle states shared by server, helper, and polling client.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OperationStatus {
    /// Accepted and waiting for the staging task.
    Queued,

    /// Release metadata and archive are being downloaded.
    Downloading,

    /// Signed inputs are durable and ready for the privileged helper.
    Staged,

    /// The helper is replacing the executable and restarting UDS.
    Applying,

    /// The replacement reported full listener readiness.
    BootConfirmed,

    /// The replacement remained active during the observation period.
    Succeeded,

    /// The previous executable was restored automatically.
    RolledBack,

    /// Staging, replacement, or restoration failed.
    Failed,
}

/// Persistent operation record returned by the status endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateOperation {
    /// Original idempotency input.
    pub request: StartUpdateRequest,

    /// Current durable lifecycle state.
    pub status: OperationStatus,

    /// RFC 3339 creation timestamp.
    pub created_at: String,

    /// RFC 3339 timestamp of the most recent state change.
    pub updated_at: String,

    /// Sanitized failure detail suitable for an administrator.
    pub error: Option<String>,
}

/// Signed UDS release manifest generated by the release workflow.
#[derive(Debug, Clone, Deserialize)]
struct UpdateManifest {
    /// Supported manifest schema revision.
    schema_version: u64,

    /// Release semantic version.
    version: String,

    /// Release build number.
    build: u64,

    /// Git tag that owns the assets.
    tag: String,

    /// Administrator-facing release notes.
    notes: String,

    /// Signed artifacts indexed by platform and architecture.
    artifacts: BTreeMap<String, UpdateArtifact>,
}

/// Platform-specific archive metadata covered by the manifest signature.
#[derive(Debug, Clone, Deserialize)]
struct UpdateArtifact {
    /// Exact archive download URL.
    url: String,

    /// Lowercase SHA-256 archive digest.
    sha256: String,

    /// Exact archive size in bytes.
    size: u64,

    /// Signed archive container format.
    archive_format: String,

    /// Only member the helper may extract.
    executable_path: String,

    /// Release-pipeline permission for executable replacement.
    self_update_supported: bool,
}

/// Minimal GitHub release representation used for paginated discovery.
#[derive(Debug, Deserialize)]
struct GithubRelease {
    /// Release tag used for exact selection.
    tag_name: String,

    /// Drafts must never be offered.
    draft: bool,

    /// Category used for strict list separation.
    prerelease: bool,

    /// Downloadable release assets.
    assets: Vec<GithubAsset>,
}

/// Download URL for a named GitHub release asset.
#[derive(Debug, Deserialize)]
struct GithubAsset {
    /// Stable asset file name.
    name: String,

    /// GitHub-provided download URL.
    browser_download_url: String,
}

/// Coordinates persistent operations for one local node.
pub struct UpdateManager {
    /// Durable operation directory below the configured data root.
    root: PathBuf,

    /// Stable identity restricting requests to this node.
    node_id: Uuid,

    /// Narrow installation capability determined at startup.
    supported: bool,

    /// Serializes idempotency and active-operation checks.
    lock: Mutex<()>,

    /// Reusable HTTPS client for official GitHub assets.
    http: reqwest::Client,
}

impl UpdateManager {
    /// Opens the operation store and determines installation capability.
    pub async fn open(config: &ServerConfig, node_id: Uuid) -> Result<Self> {
        let root = config.data_dir.join("self-update/operations");
        tokio::fs::create_dir_all(&root).await?;
        let supported = config.mode == ServerMode::SingleNode
            && cfg!(target_os = "linux")
            && std::env::current_exe().is_ok_and(|path| path == Path::new("/usr/local/bin/uds"))
            && Path::new("/etc/systemd/system/uds.service").is_file()
            && Path::new("/etc/systemd/system/uds-update.service").is_file()
            && Path::new("/etc/systemd/system/uds-update.path").is_file();
        let http = reqwest::Client::builder()
            .user_agent("uds-update-client")
            .build()
            .map_err(|error| UdsError::Storage(error.to_string()))?;
        Ok(Self {
            root,
            node_id,
            supported,
            lock: Mutex::new(()),
            http,
        })
    }

    /// Discovers all newer signed releases in one explicitly selected category.
    pub async fn releases(&self, kind: ReleaseKind) -> Result<ReleaseResponse> {
        if !self.supported {
            return Ok(self.unavailable_response());
        }
        let mut releases = Vec::new();
        for page in 1.. {
            let github: Vec<GithubRelease> = self
                .http
                .get(RELEASES_API)
                .query(&[("per_page", "100"), ("page", &page.to_string())])
                .send()
                .await
                .map_err(network_error)?
                .error_for_status()
                .map_err(network_error)?
                .json()
                .await
                .map_err(network_error)?;
            if github.is_empty() {
                break;
            }
            let count = github.len();
            for release in github {
                if release.draft || release.prerelease != (kind == ReleaseKind::Prerelease) {
                    continue;
                }
                let Ok(version) = Version::parse(release.tag_name.trim_start_matches('v')) else {
                    continue;
                };
                if version <= Version::parse(build_info::VERSION)? {
                    continue;
                }
                if let Ok((manifest, _, _)) = self.fetch_manifest(&release).await
                    && validate_manifest(&manifest, &release.tag_name, &version.to_string()).is_ok()
                {
                    releases.push(AvailableRelease {
                        version: manifest.version,
                        build: manifest.build,
                        notes: manifest.notes,
                        prerelease: release.prerelease,
                    });
                }
            }
            if count < 100 {
                break;
            }
        }
        releases.sort_by(|a, b| {
            Version::parse(&b.version)
                .ok()
                .cmp(&Version::parse(&a.version).ok())
        });
        Ok(ReleaseResponse {
            node_id: self.node_id,
            version: build_info::VERSION.into(),
            build: build_info::BUILD.parse().unwrap_or(0),
            update_supported: true,
            unavailable_reason: None,
            releases,
        })
    }

    /// Persists an idempotent request and starts asynchronous staging.
    pub async fn start(self: &Arc<Self>, request: StartUpdateRequest) -> Result<UpdateOperation> {
        let _guard = self.lock.lock().await;
        if !self.supported {
            return Err(UdsError::BadRequest(self.unavailable_reason()));
        }
        if request.node_id != self.node_id {
            return Err(UdsError::BadRequest(
                "the requested node ID is not this single node".into(),
            ));
        }
        Version::parse(&request.version).map_err(|_| UdsError::BadRequest("version must be valid SemVer".into()))?;
        if let Some(existing) = self.read(request.operation_id).await? {
            return if existing.request == request {
                Ok(existing)
            } else {
                Err(UdsError::Conflict(
                    "operation ID was already used with different input".into(),
                ))
            };
        }
        if self.active_operation().await?.is_some() {
            return Err(UdsError::Conflict(
                "this node already has an active update operation".into(),
            ));
        }
        let now = now();
        let operation = UpdateOperation {
            request,
            status: OperationStatus::Queued,
            created_at: now.clone(),
            updated_at: now,
            error: None,
        };
        self.write(&operation).await?;
        let manager = self.clone();
        let id = operation.request.operation_id;
        tokio::spawn(async move {
            if let Err(error) = manager.stage(id).await {
                let _ = manager.fail(id, &error.to_string()).await;
            }
        });
        Ok(operation)
    }

    /// Loads one durable operation by identifier.
    pub async fn get(&self, id: Uuid) -> Result<UpdateOperation> {
        self.read(id)
            .await?
            .ok_or_else(|| UdsError::NotFound("update operation does not exist".into()))
    }

    /// Downloads, verifies, and atomically stages one exact release.
    async fn stage(&self, id: Uuid) -> Result<()> {
        let mut operation = self.get(id).await?;
        self.set_status(&mut operation, OperationStatus::Downloading)
            .await?;
        let kind = if operation.request.allow_prerelease {
            ReleaseKind::Prerelease
        } else {
            ReleaseKind::Regular
        };
        let releases = self.github_releases(kind).await?;
        let github = releases
            .into_iter()
            .find(|release| release.tag_name == format!("v{}", operation.request.version))
            .ok_or_else(|| {
                UdsError::BadRequest("the exact selected release is unavailable in the chosen category".into())
            })?;
        let (manifest, manifest_bytes, signature_bytes) = self.fetch_manifest(&github).await?;
        let artifact = validate_manifest(&manifest, &github.tag_name, &operation.request.version)?;
        let archive = self
            .http
            .get(&artifact.url)
            .send()
            .await
            .map_err(network_error)?
            .error_for_status()
            .map_err(network_error)?
            .bytes()
            .await
            .map_err(network_error)?;
        validate_archive_bytes(&archive, artifact)?;
        let directory = self.root.join(id.to_string());
        tokio::fs::create_dir_all(&directory).await?;
        atomic_write(&directory.join("latest.json"), &manifest_bytes).await?;
        atomic_write(&directory.join("latest.json.sig"), &signature_bytes).await?;
        atomic_write(&directory.join("archive.tar.gz"), &archive).await?;
        self.set_status(&mut operation, OperationStatus::Staged)
            .await?;
        atomic_write(&self.root.join(format!("{id}.apply")), b"staged\n").await
    }

    /// Fetches and cryptographically verifies both manifest assets.
    async fn fetch_manifest(&self, release: &GithubRelease) -> Result<(UpdateManifest, Vec<u8>, Vec<u8>)> {
        let manifest_url = asset_url(release, "latest.json")?;
        let signature_url = asset_url(release, "latest.json.sig")?;
        let manifest = self
            .http
            .get(manifest_url)
            .send()
            .await
            .map_err(network_error)?
            .error_for_status()
            .map_err(network_error)?
            .bytes()
            .await
            .map_err(network_error)?
            .to_vec();
        let signature_text = self
            .http
            .get(signature_url)
            .send()
            .await
            .map_err(network_error)?
            .error_for_status()
            .map_err(network_error)?
            .text()
            .await
            .map_err(network_error)?;
        verify_signature(&manifest, signature_text.trim())?;
        let parsed: UpdateManifest = serde_json::from_slice(&manifest)?;
        Ok((parsed, manifest, signature_text.into_bytes()))
    }

    /// Fetches all GitHub pages for an exact release-category lookup.
    async fn github_releases(&self, kind: ReleaseKind) -> Result<Vec<GithubRelease>> {
        let mut all = Vec::new();
        for page in 1.. {
            let page_items: Vec<GithubRelease> = self
                .http
                .get(RELEASES_API)
                .query(&[("per_page", "100"), ("page", &page.to_string())])
                .send()
                .await
                .map_err(network_error)?
                .error_for_status()
                .map_err(network_error)?
                .json()
                .await
                .map_err(network_error)?;
            let count = page_items.len();
            all.extend(
                page_items
                    .into_iter()
                    .filter(|item| !item.draft && item.prerelease == (kind == ReleaseKind::Prerelease)),
            );
            if count < 100 {
                break;
            }
        }
        Ok(all)
    }

    /// Finds any nonterminal operation that prevents concurrent replacement.
    async fn active_operation(&self) -> Result<Option<UpdateOperation>> {
        let mut entries = tokio::fs::read_dir(&self.root).await?;
        while let Some(entry) = entries.next_entry().await? {
            let Ok(id) = Uuid::parse_str(&entry.file_name().to_string_lossy()) else {
                continue;
            };
            if let Some(operation) = self.read(id).await?
                && !terminal(operation.status)
            {
                return Ok(Some(operation));
            }
        }
        Ok(None)
    }

    /// Reads an operation JSON file if it exists.
    async fn read(&self, id: Uuid) -> Result<Option<UpdateOperation>> {
        let path = self.root.join(id.to_string()).join("operation.json");
        match tokio::fs::read(path).await {
            Ok(bytes) => Ok(Some(serde_json::from_slice(&bytes)?)),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error.into()),
        }
    }

    /// Atomically replaces an operation JSON file.
    async fn write(&self, operation: &UpdateOperation) -> Result<()> {
        let directory = self.root.join(operation.request.operation_id.to_string());
        tokio::fs::create_dir_all(&directory).await?;
        atomic_write(
            &directory.join("operation.json"),
            &serde_json::to_vec_pretty(operation)?,
        )
        .await
    }

    /// Changes and persists the lifecycle state.
    async fn set_status(&self, operation: &mut UpdateOperation, status: OperationStatus) -> Result<()> {
        operation.status = status;
        operation.updated_at = now();
        self.write(operation).await
    }

    /// Records a sanitized staging failure.
    async fn fail(&self, id: Uuid, message: &str) -> Result<()> {
        let mut operation = self.get(id).await?;
        operation.status = OperationStatus::Failed;
        operation.updated_at = now();
        operation.error = Some(sanitize_error(message));
        self.write(&operation).await
    }

    /// Builds the explicit unsupported response for non-wizard/fleet installs.
    fn unavailable_response(&self) -> ReleaseResponse {
        ReleaseResponse {
            node_id: self.node_id,
            version: build_info::VERSION.into(),
            build: build_info::BUILD.parse().unwrap_or(0),
            update_supported: false,
            unavailable_reason: Some(self.unavailable_reason()),
            releases: Vec::new(),
        }
    }

    /// Explains the deliberately narrow support boundary without exposing paths.
    fn unavailable_reason(&self) -> String {
        "manual UDS updates require a wizard-installed single node at /usr/local/bin/uds managed by systemd; fleet updates are planned but not available".into()
    }
}

/// Runs the privileged helper for one staged operation directory.
pub fn apply_staged(operation_dir: &Path, binary: &Path) -> Result<()> {
    let manifest_bytes = fs::read(operation_dir.join("latest.json"))?;
    let signature = fs::read_to_string(operation_dir.join("latest.json.sig"))?;
    verify_signature(&manifest_bytes, signature.trim())?;
    let manifest: UpdateManifest = serde_json::from_slice(&manifest_bytes)?;
    let artifact = validate_manifest(&manifest, &manifest.tag, &manifest.version)?;
    let archive = fs::read(operation_dir.join("archive.tar.gz"))?;
    validate_archive_bytes(&archive, artifact)?;
    let executable = extract_executable(&archive, &artifact.executable_path)?;
    let previous = binary.with_file_name("uds.previous");
    let candidate = binary.with_file_name("uds.new");
    fs::write(&candidate, executable)?;
    set_executable(&candidate)?;
    if previous.exists() {
        fs::remove_file(&previous)?;
    }
    fs::rename(binary, &previous)?;
    if let Err(error) = fs::rename(&candidate, binary) {
        let _ = fs::rename(&previous, binary);
        return Err(error.into());
    }
    Ok(())
}

/// Applies all staged operations found by the bounded systemd path trigger.
/// Note that this function is invoked by a separate systemd oneshot and
/// runs with root privileges, so it must be careful to avoid exposing any
/// untrusted input.
pub fn apply_pending(data_dir: &Path, binary: &Path) -> Result<()> {
    let root = data_dir.join("self-update/operations");
    for entry in fs::read_dir(&root)? {
        let directory = entry?.path();
        let operation_path = directory.join("operation.json");
        let Ok(bytes) = fs::read(&operation_path) else { continue };
        let mut operation: UpdateOperation = serde_json::from_slice(&bytes)?;
        if operation.status != OperationStatus::Staged {
            continue;
        }
        let marker = root.join(format!("{}.apply", operation.request.operation_id));
        update_sync(
            &operation_path,
            &mut operation,
            OperationStatus::Applying,
            None,
        )?;
        let applied = apply_staged(&directory, binary);
        if let Err(error) = applied {
            update_sync(
                &operation_path,
                &mut operation,
                OperationStatus::Failed,
                Some(&error.to_string()),
            )?;
            let _ = fs::remove_file(&marker);
            continue;
        }
        let restart = Command::new("systemctl")
            .args(["restart", "uds.service"])
            .status();
        let ready = restart.is_ok_and(|status| status.success()) && wait_active(Duration::from_secs(30));
        if ready {
            update_sync(
                &operation_path,
                &mut operation,
                OperationStatus::BootConfirmed,
                None,
            )?;
            update_sync(
                &operation_path,
                &mut operation,
                OperationStatus::Succeeded,
                None,
            )?;
            let _ = fs::remove_file(&marker);
            continue;
        }
        let previous = binary.with_file_name("uds.previous");
        let rollback = fs::remove_file(binary).and_then(|_| fs::rename(&previous, binary));
        if rollback.is_ok() {
            let restored = Command::new("systemctl")
                .args(["restart", "uds.service"])
                .status()
                .is_ok_and(|status| status.success());
            let status = if restored {
                OperationStatus::RolledBack
            } else {
                OperationStatus::Failed
            };
            let message = if restored {
                "the new version did not remain ready; the previous executable was restored"
            } else {
                "the new version failed and the restored service could not be started"
            };
            update_sync(&operation_path, &mut operation, status, Some(message))?;
        } else {
            update_sync(
                &operation_path,
                &mut operation,
                OperationStatus::Failed,
                Some("the new version failed and restoring the previous executable also failed"),
            )?;
        }
        let _ = fs::remove_file(&marker);
    }
    Ok(())
}

/// Observes systemd continuously so an early crash causes rollback.
fn wait_active(duration: Duration) -> bool {
    let started = Instant::now();
    while started.elapsed() < duration {
        let active = Command::new("systemctl")
            .args(["is-active", "--quiet", "uds.service"])
            .status()
            .is_ok_and(|status| status.success());
        if !active {
            return false;
        }
        std::thread::sleep(Duration::from_secs(1));
    }
    true
}

/// Persists helper state atomically for polling after restart.
fn update_sync(
    path: &Path,
    operation: &mut UpdateOperation,
    status: OperationStatus,
    error: Option<&str>,
) -> Result<()> {
    operation.status = status;
    operation.updated_at = now();
    operation.error = error.map(sanitize_error);
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, serde_json::to_vec_pretty(operation)?)?;
    fs::rename(temporary, path)?;
    Ok(())
}

/// Validates signed manifest invariants and selects this host's artifact.
fn validate_manifest<'a>(manifest: &'a UpdateManifest, tag: &str, version: &str) -> Result<&'a UpdateArtifact> {
    if manifest.schema_version != 1
        || manifest.version != version
        || manifest.tag != tag
        || tag != format!("v{version}")
    {
        return Err(UdsError::BadRequest(
            "signed manifest version or tag is inconsistent".into(),
        ));
    }
    let parsed = Version::parse(version)?;
    if parsed <= Version::parse(build_info::VERSION)? {
        return Err(UdsError::BadRequest(
            "selected version is not newer than the running version".into(),
        ));
    }
    let key = format!("linux-{}", std::env::consts::ARCH);
    let artifact = manifest
        .artifacts
        .get(&key)
        .ok_or_else(|| UdsError::BadRequest("signed manifest has no artifact for this Linux architecture".into()))?;
    if !artifact.self_update_supported || artifact.archive_format != "tar.gz" || artifact.size == 0 {
        return Err(UdsError::BadRequest(
            "signed artifact is not eligible for this update workflow".into(),
        ));
    }
    Ok(artifact)
}

/// Verifies the raw manifest bytes with the embedded Ed25519 public key.
fn verify_signature(manifest: &[u8], encoded: &str) -> Result<()> {
    let key = VerifyingKey::from_public_key_pem(UPDATE_PUBLIC_KEY)
        .map_err(|_| UdsError::BadRequest("embedded update key is invalid".into()))?;
    verify_signature_with_key(&key, manifest, encoded)
}

/// Verifies a signature with an injected key so tests never use production secrets.
fn verify_signature_with_key(key: &VerifyingKey, manifest: &[u8], encoded: &str) -> Result<()> {
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .map_err(|_| UdsError::BadRequest("manifest signature is not valid base64".into()))?;
    let signature = Signature::from_slice(&bytes)
        .map_err(|_| UdsError::BadRequest("manifest signature has an invalid length".into()))?;
    key.verify(manifest, &signature)
        .map_err(|_| UdsError::BadRequest("manifest signature verification failed".into()))
}

/// Checks archive size and digest against the signed artifact metadata.
fn validate_archive_bytes(bytes: &[u8], artifact: &UpdateArtifact) -> Result<()> {
    if bytes.len() as u64 != artifact.size {
        return Err(UdsError::BadRequest(
            "archive size does not match the signed manifest".into(),
        ));
    }
    let digest = hex::encode(Sha256::digest(bytes));
    if digest != artifact.sha256.to_ascii_lowercase() {
        return Err(UdsError::BadRequest(
            "archive digest does not match the signed manifest".into(),
        ));
    }
    Ok(())
}

/// Extracts exactly one regular executable entry without unpacking other files.
fn extract_executable(bytes: &[u8], signed_path: &str) -> Result<Vec<u8>> {
    let path = Path::new(signed_path);
    if path.is_absolute()
        || path
            .components()
            .any(|part| !matches!(part, Component::Normal(_)))
    {
        return Err(UdsError::BadRequest(
            "signed executable path is unsafe".into(),
        ));
    }
    let decoder = flate2::read::GzDecoder::new(bytes);
    let mut archive = tar::Archive::new(decoder);
    let mut found = None;
    for entry in archive
        .entries()
        .map_err(|_| UdsError::BadRequest("archive is corrupt".into()))?
    {
        let mut entry = entry.map_err(|_| UdsError::BadRequest("archive is corrupt".into()))?;
        let entry_path = entry
            .path()
            .map_err(|_| UdsError::BadRequest("archive path is invalid".into()))?;
        if entry_path.is_absolute()
            || entry_path
                .components()
                .any(|part| !matches!(part, Component::Normal(_)))
            || entry.header().entry_type().is_symlink()
            || entry.header().entry_type().is_hard_link()
        {
            return Err(UdsError::BadRequest(
                "archive contains an unsafe path or link".into(),
            ));
        }
        if entry_path.as_ref() == path {
            if !entry.header().entry_type().is_file() || found.is_some() {
                return Err(UdsError::BadRequest(
                    "archive executable is missing, ambiguous, or not a regular file".into(),
                ));
            }
            let mut content = Vec::new();
            entry.read_to_end(&mut content)?;
            found = Some(content);
        }
    }
    found.ok_or_else(|| UdsError::BadRequest("archive does not contain the signed executable path".into()))
}

/// Locates a required asset in one GitHub release.
fn asset_url<'a>(release: &'a GithubRelease, name: &str) -> Result<&'a str> {
    release
        .assets
        .iter()
        .find(|asset| asset.name == name)
        .map(|asset| asset.browser_download_url.as_str())
        .ok_or_else(|| UdsError::BadRequest(format!("release is missing {name}")))
}

/// Converts transport failures without exposing request internals to API users.
fn network_error(error: reqwest::Error) -> UdsError {
    UdsError::Storage(format!("release service request failed: {error}"))
}

/// Writes bytes through a same-directory temporary file and atomic rename.
async fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    let temporary = path.with_extension("tmp");
    tokio::fs::write(&temporary, bytes).await?;
    tokio::fs::rename(temporary, path).await?;
    Ok(())
}

/// Returns an RFC 3339 UTC timestamp for durable operation records.
fn now() -> String {
    time::OffsetDateTime::now_utc()
        .format(&time::format_description::well_known::Rfc3339)
        .unwrap_or_else(|_| "unknown".into())
}

/// Limits persistent error text to a safe, single-line administrative detail.
fn sanitize_error(message: &str) -> String {
    message
        .lines()
        .next()
        .unwrap_or("update failed")
        .chars()
        .take(300)
        .collect()
}

/// Reports whether a lifecycle state releases the node's operation lock.
fn terminal(status: OperationStatus) -> bool {
    matches!(
        status,
        OperationStatus::Succeeded | OperationStatus::RolledBack | OperationStatus::Failed
    )
}

/// Applies executable permissions to the staged replacement on Unix.
#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o755))?;
    Ok(())
}

/// Keeps non-Unix builds compilable even though applying is unsupported there.
#[cfg(not(unix))]
fn set_executable(_path: &Path) -> Result<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};
    use flate2::Compression;

    /// Creates an in-memory tar.gz with one chosen entry type.
    fn archive(path: &str, bytes: &[u8]) -> Vec<u8> {
        let output = Vec::new();
        let encoder = flate2::write::GzEncoder::new(output, Compression::default());
        let mut builder = tar::Builder::new(encoder);
        let mut header = tar::Header::new_gnu();
        header.set_size(bytes.len() as u64);
        header.set_mode(0o755);
        header.set_cksum();
        builder.append_data(&mut header, path, bytes).unwrap();
        builder.into_inner().unwrap().finish().unwrap()
    }

    /// Accepts a test-key signature and rejects modified manifest bytes.
    #[test]
    fn signature_rejects_tampering() {
        let signing = SigningKey::from_bytes(&[7; 32]);
        let verifying = signing.verifying_key();
        let manifest = b"signed manifest";
        let signature = base64::engine::general_purpose::STANDARD.encode(signing.sign(manifest).to_bytes());
        assert!(verify_signature_with_key(&verifying, manifest, &signature).is_ok());
        assert!(verify_signature_with_key(&verifying, b"modified manifest", &signature).is_err());
    }

    /// Extracts only the exact signed regular executable member.
    #[test]
    fn archive_extracts_exact_executable() {
        let bytes = archive("release/uds", b"binary");
        assert_eq!(
            extract_executable(&bytes, "release/uds").unwrap(),
            b"binary"
        );
        assert!(extract_executable(&bytes, "release/other").is_err());
    }

    /// Rejects a signed path containing parent traversal.
    #[test]
    fn archive_rejects_path_traversal() {
        let bytes = archive("release/uds", b"binary");
        assert!(extract_executable(&bytes, "../uds").is_err());
    }

    /// Detects both signed archive size and digest mismatches.
    #[test]
    fn archive_metadata_must_match() {
        let artifact = UpdateArtifact {
            url: "https://example.invalid/archive".into(),
            sha256: hex::encode(Sha256::digest(b"archive")),
            size: 7,
            archive_format: "tar.gz".into(),
            executable_path: "release/uds".into(),
            self_update_supported: true,
        };
        assert!(validate_archive_bytes(b"archive", &artifact).is_ok());
        assert!(validate_archive_bytes(b"changed", &artifact).is_err());
    }
}
